//! Runtime contamination guard for the V_X training pipeline.
//!
//! Refuses to load a training-features CSV that contains any
//! reference basename listed in the 2026-05-14 KADID/TID overlap
//! audit. The blocklist is embedded as `static BLOCKLIST` below
//! so the trainer cannot accidentally load contaminated data even
//! if a stale CSV is on disk somewhere.
//!
//! ## Provenance
//!
//! The blocklist is the union of:
//! - `zensim/benchmarks/kadid_overlap_2026-05-14.tsv` rows with
//!   hamming ≤ 16 (118 sources, KADID I01..I81 overlap)
//! - `zensim/benchmarks/tid_overlap_2026-05-14.tsv` rows with
//!   hamming ≤ 16 (33 sources, TID I01..I25 overlap)
//! - dedup union = 149 unique source basenames
//!
//! Both audits used dHash-64 against the synth-v2 training-source
//! corpus at /mnt/v/input/zensim/sources/.
//!
//! ## Usage
//!
//! Trainer code calls
//! `contamination_guard::scrub_csv_or_die(csv_path)` once per CSV
//! before constructing the training group. The function returns
//! `Ok(())` if the CSV is clean; on any blocklisted basename it
//! prints a loud error and exits with status 2.
//!
//! See `zensim/CLAUDE.md` "Dataset contamination rules" for the
//! policy this enforces.

use std::collections::HashSet;
use std::fs::File;
use std::io::{BufRead, BufReader};
use std::path::Path;

/// The blocklist text is committed at
/// `zensim/benchmarks/contamination_blocklist_2026-05-14.txt`
/// (149 basenames, one per line, no extension). Generated by:
///
///     cat zensim/benchmarks/kadid_overlap_2026-05-14.tsv \
///         zensim/benchmarks/tid_overlap_2026-05-14.tsv \
///     | awk -F'\t' 'NR>1 && $5<=16 \
///         {n=split($1,p,"/"); fname=p[n]; \
///          sub(/\.png$/, "", fname); print fname}' \
///     | sort -u
///
/// The trainer + bake pipeline reads this list at compile time via
/// `include_str!` so a stale or missing file at run time can't
/// disable the guard.
static BLOCKLIST_TXT: &str =
    include_str!("../../benchmarks/contamination_blocklist_2026-05-14.txt");

pub fn blocklist() -> HashSet<&'static str> {
    BLOCKLIST_TXT
        .lines()
        .map(|l| l.trim())
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
        .collect()
}

pub fn scrub_csv_or_die<P: AsRef<Path>>(csv_path: P) -> std::io::Result<()> {
    let path = csv_path.as_ref();
    if path
        .file_name()
        .and_then(|n| n.to_str())
        .map(|s| s.contains("CONTAMINATED"))
        .unwrap_or(false)
    {
        eprintln!(
            "REFUSE: input CSV {} is explicitly tagged CONTAMINATED. \
             Use a canonical clean CSV from /mnt/v/zen/zensim-training/2026-05-14-clean/ instead.",
            path.display()
        );
        std::process::exit(2);
    }
    let f = File::open(path)?;
    let mut r = BufReader::new(f);
    let mut header = String::new();
    r.read_line(&mut header)?;
    let bl = blocklist();
    let mut bad: Vec<String> = Vec::new();
    let mut total: usize = 0;
    for line in r.lines() {
        let line = match line {
            Ok(l) => l,
            Err(_) => continue,
        };
        if let Some(idx) = line.find(',') {
            let basename = &line[..idx];
            total += 1;
            if bl.contains(basename) {
                if bad.len() < 10 {
                    bad.push(basename.to_string());
                }
            }
        }
    }
    if !bad.is_empty() {
        eprintln!(
            "\nCONTAMINATION DETECTED in {} ({} rows checked, {} blocklisted basenames found, first 10):",
            path.display(),
            total,
            bad.len()
        );
        for b in &bad {
            eprintln!("    - {b}");
        }
        eprintln!(
            "\nThe 149-basename blocklist is the 2026-05-14 KADID+TID perceptual-overlap audit."
        );
        eprintln!(
            "Re-purge the CSV (or use the canonical clean CSV at /mnt/v/zen/zensim-training/2026-05-14-clean/safe_synth_v19_clean_features.csv) before training.\n"
        );
        std::process::exit(2);
    }
    eprintln!(
        "contamination_guard: {} clean ({} rows checked, 0 blocklisted)",
        path.display(),
        total
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn blocklist_has_expected_size() {
        assert_eq!(blocklist().len(), 149,
            "2026-05-14 KADID+TID overlap audit produced 149 unique basenames; \
             if this asserts, the blocklist file was changed without updating the test");
    }
    #[test]
    fn blocklist_contains_known_offender() {
        // I18 had 4 size variants of `gmessages` in the KADID overlap.
        let bl = blocklist();
        assert!(bl.contains("gmessages_1022x818"), "gmessages_1022x818 expected in blocklist");
    }
}
