# zensim dev commands

# The rustdoc-JSON nightly is PINNED (keep in sync with the `api-doc-check`
# job in .github/workflows/ci.yml): an unpinned tracking nightly churns
# cross-crate path rendering with zero repo changes — MEASURED 2026-09-06,
# regenerating zensim-regress.txt against a newer nightly than the one that
# produced the committed snapshot rewrote 11 lines of `std::io::error::Error`
# to `core::io::error::Error` (the core::io re-homing), which is exactly the
# false-diff class this pin exists to prevent. Bump the pin deliberately, in
# the same commit as a `just api-doc` regen.
apidoc_toolchain := "nightly-2026-09-02"

# Format + regenerate the public-API surface snapshots (docs/public-api/).
# The snapshot runner lives in the workspace-excluded apidoc/ package, so it
# is never built or run by plain `cargo test`, nor by any OTHER CI job — only
# the dedicated `api-doc-check` CI job (which sets ZEN_API_DOC=check) runs it.
fmt:
    cargo fmt --all
    ZEN_API_DOC_TOOLCHAIN={{apidoc_toolchain}} cargo test --manifest-path apidoc/Cargo.toml

# Regenerate the public-API surface snapshots only
api-doc:
    ZEN_API_DOC_TOOLCHAIN={{apidoc_toolchain}} cargo test --manifest-path apidoc/Cargo.toml

# Verify the committed snapshots are current (what CI's api-doc-check job runs)
api-doc-check:
    ZEN_API_DOC=check ZEN_API_DOC_TOOLCHAIN={{apidoc_toolchain}} cargo test --manifest-path apidoc/Cargo.toml

# Explicit caller-owned TRAIN corpus gate. The caller selects the four
# canonical, SHA-checked references; there is no silent skip when absent.
# All generated bytes and cargo targets go under /var/tmp/gmsbank/.
#   GMSBANK_CORPUS_REFS=/var/tmp/gmsbank/corpus_probe/refs.tsv just gmsbank-corpus
[doc("Run GMSBANK's four-reference TRAIN blur/noise/zenjpeg response gate")]
gmsbank-corpus:
    #!/usr/bin/env bash
    set -euo pipefail
    : "${GMSBANK_CORPUS_REFS:?set GMSBANK_CORPUS_REFS to the SHA-checked four-reference TRAIN TSV}"
    export CARGO_TARGET_DIR=/var/tmp/gmsbank/target
    export ZENSIM_FORMULA_REV=3
    export ZENSIM_ROOT_FORM=sqrt
    root=/var/tmp/gmsbank/corpus_probe
    mkdir -p "$root"
    /home/lilith/tmp/devin/heavy --mem 16G --jobs 8 -- cargo build --release --manifest-path zensim-bench/Cargo.toml --example gmsbank_corpus_fixtures --features m3-fixtures,zen-decode
    /home/lilith/tmp/devin/heavy --mem 16G --jobs 8 -- "$CARGO_TARGET_DIR/release/examples/gmsbank_corpus_fixtures" "$GMSBANK_CORPUS_REFS" "$root"
    /home/lilith/tmp/devin/heavy --mem 16G --jobs 8 -- cargo build --release --manifest-path zensim-bench/Cargo.toml --example extract_features_372col --features training,zen-decode
    /home/lilith/tmp/devin/heavy --mem 16G --jobs 8 -- "$CARGO_TARGET_DIR/release/examples/extract_features_372col" --corpus pairs-tsv --path "$root/pairs.tsv" --out "$root/features.csv" --full-gmsbank --input-contract legacy-rgb8
    python3 scripts/gmsbank/corpus_response.py "$root/features.csv"

# Explicit opt-in for mounted Rev4 TRAIN corpora. The two ignored tests fail
# on absent inputs or unexpected unsupported formats. The unignored 16-pair
# synthetic parity gate runs in the ordinary all-features CI test job.
# Run this recipe through the local heavy lock when building on the lab host.
[positional-arguments]
rev4-corpus-tests root kadid_inputs expected_unsupported_safesyn:
    #!/usr/bin/env bash
    set -euo pipefail
    export ZENSIM_REV4_CORPUS_ROOT="$1"
    export ZENSIM_REV4_KADID_INPUTS="$2"
    export ZENSIM_REV4_EXPECT_UNSUPPORTED_SAFESYN="$3"
    cargo test -p zensim --release --all-features --test rev4_featbank_parity rev4_synthetic_16_pair_identity -- --nocapture
    cargo test -p zensim --release --all-features --lib rev4_gridblk_zenjpeg_ladder -- --ignored --nocapture
    cargo test -p zensim --release --all-features --test rev4_featbank_parity rev4_corpus_toggle_identity -- --ignored --nocapture

# CI-exact clippy
clippy:
    cargo clippy --workspace --all-targets --all-features --exclude zensim-wasm-tests -- -D warnings

# Quick offline rank/dial report (not full-eval or product qualification).
# Emits markdown plus a self-contained HTML report. Optional REF
# bake enables the per-zone dial-agreement panel; RAMP grid enables the
# severity-ramp monotonicity section (point it at a regime-matched parquet).
#   just metric-eval zensim/weights/b_sdr_linear_cid80_inclwinsor_dense_dial_2026-07-07.bin
#   just metric-eval <bake> <ref-bake> <ramp-grid.parquet>
[doc("Quick offline rank/dial report; not full-eval or product qualification")]
[positional-arguments]
metric-eval bake ref="" ramp="" out="/mnt/v/output/zensim/reports":
    #!/usr/bin/env bash
    set -euo pipefail
    bake=$1
    ref=$2
    ramp=$3
    out=$4
    cargo build --release -p zensim-validate --bin bake_verdict
    mkdir -p "$out"
    stem=$(basename "$bake" .bin)
    args=(--bake "$bake" --output "$out/$stem.md" --html "$out/$stem.html")
    if [[ -n "$ref" ]]; then args+=(--compare "$ref"); fi
    if [[ -n "$ramp" ]]; then args+=(--ramp-grid "$ramp"); fi
    "${CARGO_TARGET_DIR:-target}/release/bake_verdict" "${args[@]}"
    echo "report: $out/$stem.html"

# Build the viewable spatial-diffmap demo gallery: six imazen-26 TRAIN sources
# x a zenjpeg q20/q50/q80 ladder, each rendered as a zensim diffmap heatmap and
# overlay, laid out as one self-contained page under /mnt/v/output (served at
# localhost:3300). A DEMO, not evidence -- one pass, no replication, no ranking
# claim. Extra args pass through (--max-dim / --profile / --scale-max / --out).
#   just demo-diffmap
#   just demo-diffmap --profile d --max-dim 1200
[doc("Build the spatial-diffmap heatmap demo gallery (demo, not evidence)")]
[positional-arguments]
demo-diffmap *options:
    python3 scripts/demos/diffmap_gallery.py "$@"

# Join the cross-generation speed matrix to the board's full-evaluation rows
# and lay the result out as one self-contained speed-vs-accuracy page under
# /mnt/v/output (served at localhost:3300). Runs NOTHING -- no benchmark, no
# scorer, no cargo -- every number is read out of files that already exist,
# and an arm with no provable accuracy row is drawn on the speed axis alone
# rather than given a lookalike row's value. Also refreshes the committed
# joined table in benchmarks/. `--raster` additionally writes PNGs of the
# charts (needs `resvg` on PATH) so the result can be looked at.
#   just demo-speed-accuracy
#   just demo-speed-accuracy --raster --out ~/tmp/speed-accuracy
[doc("Speed-vs-accuracy page from the speed matrix + board rows (demo, joins existing data)")]
[positional-arguments]
demo-speed-accuracy *options:
    python3 scripts/demos/speed_accuracy_page.py "$@"

# Fail on scripts that cannot run: pinned to a deleted sibling worktree, or
# hardcoding a binary with no source anywhere. On 2026-07-15 an audit found 25
# of 130 scripts in scripts/v_next/ pointing into worktrees that had been
# cleaned up weeks earlier, plus one that had not PARSED since a bulk sed.
# Nobody noticed because nobody ran them. This is the check that notices.
lint-scripts:
    python3 scripts/lint_scripts.py

# Paired arithmetic-revision cost A/B (issue #61). Builds the interleaved
# extraction instrument ONCE and runs it in alternating revision-1/revision-3
# blocks on one pinned core, with `fast_ssim2` as the cross-block drift anchor.
# Do NOT wrap in run-heavy — its cgroup makes zenbench's gating refuse the run.
#   just rev3-cost ~/tmp/rev3-cost 2 1024,2048 8
[positional-arguments]
rev3-cost out blocks="2" sizes="1024,2048" cpu="8":
    cargo bench --no-run --locked --bench extract_paths_bench -p zensim \
        --features custom-profiles,feature-regime-v2,threads,training
    ./scripts/bench/rev3_cost_ab.sh "$1" "$2" "$3" "$4"
    python3 scripts/bench/rev3_cost_report.py "$1"

# Peak-RSS half of the revision cost question: `/usr/bin/time -v` max RSS per
# arm per revision, one arm per process so the reading is attributable.
#   just rev3-rss ~/tmp/rev3-rss
# Two BUILDS at the default revision, alternating blocks on one pinned core:
# "what did the default path pay between commit X and commit Y". Copy both
# bench binaries to equal-length paths first (argv[0] length shifts layout).
#   just perf-ab-binaries ~/tmp/ab-run ~/tmp/ab/bin_A ~/tmp/ab/bin_B
[positional-arguments]
perf-ab-binaries out bin_a bin_b blocks="2" sizes="1024,2048" cpu="8":
    BIN_A="$2" BIN_B="$3" ./scripts/bench/rev3_cost_ab.sh "$1" "$4" "$5" "$6"
    python3 scripts/bench/rev3_cost_report.py "$1"

[positional-arguments]
rev3-rss out sizes="1024 2048" arms="buf_v1_372 fold372_full fold944_full" cpu="8":
    ./scripts/bench/rev3_rss.sh "$1" "$2" "$3" "$4"

# Replay the registered spatial coherence cells at revision 1 and revision 3.
# ARMS THE CROSS-REVISION DIAGNOSTIC BYPASS: the bakes were fit at revision 1,
# so this measures what the extraction change does to a FIXED model. Not a
# qualification, not model quality. See the script header.
[positional-arguments]
rev3-spatial out:
    ./scripts/bench/rev3_spatial_replay.sh "$1"

# The cross-generation speed matrix: every named zensim profile, the two
# frozen Rev3 ensembles, and the peer metrics (fast-ssim2, butteraugli,
# ssimulacra2/rust-av) interleaved across 64/256/1024/2048/4096 squares at 1
# and 16 threads. Builds BOTH fast-ssim2 feature configurations, because its
# rayon parallelism is a cargo feature and an MT row measured against a
# single-threaded opponent is not an MT comparison.
# The BUILDS go through run-heavy; the RUNS deliberately do not (its cgroup
# makes zenbench's own gating refuse the run — see rev3-cost above).
#   just bench-speed-matrix
[doc("Cross-generation + peer-metric speed matrix (writes raw rounds, then the summary)")]
[positional-arguments]
bench-speed-matrix raw="/mnt/v/output/zensim/demos/speed-matrix-2026-09-18/raw" stem="benchmarks/speed_matrix_2026-09-18":
    #!/usr/bin/env bash
    set -euo pipefail
    raw=$1
    stem=$2
    # cargo prints one JSON message per line; run-heavy's own chatter is not
    # JSON, so the `^{` filter keeps the two apart without swallowing errors.
    build() {
        ~/work/zen/scripts/run-heavy --mem 16G --jobs 8 -- \
            cargo bench --no-run --message-format=json-render-diagnostics \
            --manifest-path zensim-bench/Cargo.toml --bench ssim2_speed_bar "$@" \
        | grep '^{' \
        | python3 -c "import json,sys; print(next(e for e in (json.loads(l).get('executable') for l in sys.stdin) if e and 'ssim2_speed_bar' in e))"
    }
    BIN_PLAIN=$(build) BIN_RAYON=$(build --features ssim2-rayon) \
        scripts/demos/speed_matrix_run.sh "$raw"
    python3 scripts/demos/speed_matrix_report.py --raw-dir "$raw" \
        --out-json "$stem.json" --out-md "$stem.md" --notes "$stem.notes.md"

# Report only, never fails — for a quick survey.
lint-scripts-list:
    python3 scripts/lint_scripts.py --list

# Target orientation vs raw human labels, every registered eval root.
check-orientation:
    python3 scripts/canonical_corpus/check_target_orientation.py --all-roots

# Which mix legs an external orientation check can reach.
check-provenance:
    python3 scripts/canonical_corpus/check_target_orientation.py --provenance

# Audit THIS recipe's data. Pass owner options explicitly (root remaps, twins,
# leakage roots); no hardcoded August campaign is silently substituted.
# Example: just check-mix path/to/bake.bin.spec.json --leak-eval-root /data/eval
[doc("Audit the supplied recipe's data; pass root/remap/leakage options explicitly")]
[positional-arguments]
check-mix spec *options:
    #!/usr/bin/env bash
    set -euo pipefail
    spec=$1
    shift
    exec python3 scripts/canonical_corpus/check_table_integrity.py --mix-from-spec "$spec" "$@"

# Orientation/provenance plus the supplied recipe's structural data audit.
[positional-arguments]
check-data spec *options:
    #!/usr/bin/env bash
    set -euo pipefail
    spec=$1
    shift
    just check-provenance
    just check-orientation
    just check-mix "$spec" "$@"

# Run the existing offline+coherence owner; this does not run the codec exam.
# Regime is explicit; an optional fourth argument overrides the feature root.
[doc("Offline + coherence evaluation: bake, name, regime, optional feature root")]
[positional-arguments]
full-eval bake name regime root="":
    #!/usr/bin/env bash
    set -euo pipefail
    exec scripts/run_full_eval.sh "$@"

# Render recorded verdicts with the current summer-gauntlet owner.
[positional-arguments]
compare fulleval_dir out *options:
    #!/usr/bin/env bash
    set -euo pipefail
    fulleval_dir=$1
    out=$2
    shift 2
    python3 scripts/v_next/gauntlet.py --fulleval-dir "$fulleval_dir" --out "$out" "$@"
    scripts/v_next/gauntlet_gates.sh "$out" "$fulleval_dir"

# THE CROSS-LIBC GATE (F18 + F19, `zensim::det_math`): build the feature dump
# for glibc AND static musl from THIS commit and compare `to_bits()` over the
# 20-cell parity matrix + 200 ladder cells. Sweeps the 2x2 of the two era knobs
# (`ZENSIM_ROOT_FORM` x `ZENSIM_POW_FORM`) as RUNTIME env vars on the same pair
# of binaries, so only one thing varies per cell, and gates the FEATURES and the
# SCORE separately -- they are two independent defects, and the `sqrt`+`libm`
# cell is what MEASURES that (F18's fix leaves the score exactly as
# libc-dependent as it found it: 1 of 220). Revision 1 MUST differ on BOTH
# columns (the negative controls) and revision 2 MUST be bit-identical on both.
# Needs `rustup target add x86_64-unknown-linux-musl`; no container.
check-cross-libc:
    ./scripts/verify_cross_libc_features.sh

# SAME-CLASS golden check for zensim-validate/tests/legacy_bake_sha.rs: the
# PINNED sha256 digests in that file were measured on THIS box (Zen 4 /
# AVX-512) and are not bit-reproducible on other SIMD tiers/platforms — CI runs
# the in-process A/B in that file's default (env-unset) path instead. Run this
# ONLY on the Zen 4 / AVX-512 dev box that captured PINNED, after touching
# anything in mlp_train's polarity-sensitive sites, to confirm the same-class
# digests still hold.
legacy-bake-zen4-golden:
    ZENSIM_ZEN4_GOLDEN_BAKE_SHA=1 cargo test -p zensim-validate --test legacy_bake_sha -- --nocapture
