#!/usr/bin/env python3
"""Parse `/tmp/reeval_logs/*.log` from dataset_metric_baseline runs
and consolidate the Mohammadi full panel rows into one markdown
comparison table per corpus.

Each log contains aggregate panel tables in the format:

  ### KADIK10k (n=10125)
  ## Full-stat panel
  | Metric | SROCC | PLCC | KROCC | OR | PWRC | Z-RMSE |
  |---|---:|---:|---:|---:|---:|---:|
  | V0_4 (bake) | 0.9461 | ... | ... | ... | ... | ... |
  | fast-ssim2  | 0.8133 | ... | ... | ... | ... | ... |
  ...

For each log file, extract the V0_4 row per corpus + label by file
basename, then emit a single markdown doc with the aggregated table.

Usage:
  python3 scripts/v_next/v0_20_parse_reeval_logs.py \\
    --log-dir /tmp/reeval_logs \\
    --out benchmarks/falsification_reeval_results_2026-05-15.md
"""
from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path


@dataclass
class PanelRow:
    bake: str
    corpus: str
    n: int | None
    srocc: float | None
    plcc: float | None
    krocc: float | None
    or_: float | None
    pwrc: float | None
    z_rmse: float | None


def parse_log(path: Path) -> list[PanelRow]:
    """Extract V0_4 panel rows per corpus from one log."""
    out: list[PanelRow] = []
    if not path.is_file():
        return out
    text = path.read_text(errors="ignore")
    bake_name = path.stem
    # Anchor each corpus section by its header. The exact section
    # title varies (KADIK10k / TID2013 / CID22). We find each header
    # and then scan forward for the next "V0_4" or "(bake)" row.
    corpora = [
        ("KADIK10k", r"=== KADIK10k \(n=(\d+)\) ==="),
        ("TID2013",  r"=== TID2013 \(n=(\d+)\) ==="),
        ("CID22",    r"=== CID22 \(n=(\d+)\) ==="),
    ]
    for corpus, header_pat in corpora:
        h = re.search(header_pat, text)
        if not h:
            continue
        n = int(h.group(1))
        start = h.end()
        # Next "=== " header bounds this section
        nxt = re.search(r"=== \w", text[start:])
        end = start + (nxt.start() if nxt else len(text) - start)
        section = text[start:end]
        # Find the full-stat panel row for "V0_4" or "(bake)". The
        # first column is the metric/bake label.
        row_pat = re.compile(
            r"\|\s*(?:V0_4|V0_4 \(bake\)|V_18.*ship|.*bake.*)\s*\|"
            r"\s*([-\d.nN/aA]+)\s*\|"  # SROCC
            r"\s*([-\d.nN/aA]+)\s*\|"  # PLCC
            r"\s*([-\d.nN/aA]+)\s*\|"  # KROCC
            r"\s*([-\d.nN/aA]+)\s*\|"  # OR
            r"\s*([-\d.nN/aA]+)\s*\|"  # PWRC
            r"\s*([-\d.nN/aA]+)\s*\|"  # Z-RMSE
        )
        def f(s: str) -> float | None:
            s = s.strip()
            try:
                return float(s)
            except (ValueError, TypeError):
                return None
        # Prefer the "Full-stat panel" subsection if present
        panel_anchor = re.search(r"##+ Full-stat panel", section)
        scan = section[panel_anchor.start():] if panel_anchor else section
        m = row_pat.search(scan)
        if not m:
            # Fall back to the legacy 5-col panel that only emits SROCC
            # — leave the rest None
            srocc_pat = re.compile(
                r"\|\s*V0_4.*?\|\s*\d+\s*\|\s*[-\d.]+\s*\|\s*([-\d.]+)"
            )
            m2 = srocc_pat.search(section)
            if m2:
                out.append(PanelRow(
                    bake=bake_name, corpus=corpus, n=n,
                    srocc=f(m2.group(1)),
                    plcc=None, krocc=None, or_=None, pwrc=None, z_rmse=None,
                ))
            continue
        out.append(PanelRow(
            bake=bake_name, corpus=corpus, n=n,
            srocc=f(m.group(1)),
            plcc=f(m.group(2)),
            krocc=f(m.group(3)),
            or_=f(m.group(4)),
            pwrc=f(m.group(5)),
            z_rmse=f(m.group(6)),
        ))
    return out


def fmt(v: float | None, fmt_str: str = "{:.4f}") -> str:
    if v is None:
        return "—"
    return fmt_str.format(v)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--log-dir", required=True, type=Path)
    ap.add_argument("--out", required=True, type=Path)
    args = ap.parse_args()

    rows: list[PanelRow] = []
    for log in sorted(args.log_dir.glob("*.log")):
        if log.name.startswith("_"):
            continue
        rows.extend(parse_log(log))

    by_corpus: dict[str, list[PanelRow]] = {}
    for r in rows:
        by_corpus.setdefault(r.corpus, []).append(r)

    out_lines = [
        "# Falsification re-eval — full Mohammadi panel (2026-05-15)",
        "",
        "Generated by `scripts/v_next/v0_20_parse_reeval_logs.py` from",
        "`/tmp/reeval_logs/*.log` (dataset_metric_baseline runs).",
        "",
        "Bakes evaluated: see `benchmarks/falsification_reeval_triage_2026-05-15.md`",
        "for the triage that produced this set.",
        "",
    ]

    for corpus in ("KADIK10k", "TID2013", "CID22"):
        out_lines.append(f"## {corpus}")
        out_lines.append("")
        out_lines.append(
            "| Bake | n | SROCC | PLCC | KROCC | OR | PWRC | Z-RMSE |"
        )
        out_lines.append("|---|---:|---:|---:|---:|---:|---:|---:|")
        for r in by_corpus.get(corpus, []):
            out_lines.append(
                f"| {r.bake} | {r.n} | {fmt(r.srocc)} | {fmt(r.plcc)} "
                f"| {fmt(r.krocc)} | {fmt(r.or_)} | {fmt(r.pwrc)} "
                f"| {fmt(r.z_rmse, '{:.3f}')} |"
            )
        out_lines.append("")

    out_lines.append("## Verdict — did SROCC-only gating miss anything?")
    out_lines.append("")
    out_lines.append(
        "For each bake, compare the row to the V_18 ship row in"
        " `v0_20_all_bakes_stat_comparison_2026-05-15.md`. A verdict"
        " FLIPS if CID22 Z-RMSE or PWRC is ≥ V_18 ship's"
        " (0.455 / 0.9373) while SROCC is within −0.01 of V_18's"
        " 0.8933 — meaning the bake is at-or-better on the absolute-"
        "error / weighted-rank stats even if SROCC drops slightly."
    )
    out_lines.append("")
    out_lines.append(
        "Verdict fill-in is manual after table inspection."
    )

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(out_lines) + "\n")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
