//! SIMD consistency testing via archmage token permutations.
//!
//! Runs an image operation under every available SIMD tier (AVX-512, AVX2,
//! SSE2, NEON, scalar) and verifies all tiers produce equivalent output.
//! Catches vectorization bugs, accumulator ordering differences, and
//! NaN-handling divergence across SIMD implementations.
//!
//! Wraps [`archmage::testing::for_each_token_permutation()`] with
//! zensim-regress comparison, forensic diff output, and optional
//! `.checksums` integration.
//!
//! Requires the `archmage` feature.
//!
//! # Which zen crates should use this?
//!
//! Any crate using `#[arcane]`, `#[autoversion]`, or `#[rite]`:
//! zenresize, zenfilters, zenpixels-convert, linear-srgb, zenjpeg,
//! zenwebp, zengif, zenpng, zenjxl-decoder, fast-ssim2, zensim.
//!
//! # Example
//!
//! ```rust,ignore
//! use zensim_regress::simd::*;
//! use zensim_regress::RegressionTolerance;
//! use archmage::testing::CompileTimePolicy;
//!
//! #[test]
//! fn resize_simd_consistency() {
//!     let input = load_test_image();
//!
//!     let report = check_simd_consistency(
//!         || {
//!             let output = resize(&input, 256, 256, Filter::Lanczos3);
//!             (output.to_rgba8(), 256, 256)
//!         },
//!         &RegressionTolerance::off_by_one(),
//!         CompileTimePolicy::Warn,
//!     ).unwrap();
//!
//!     assert!(report.all_passed, "{report}");
//! }
//! ```
//!
//! # Idiomatic patterns
//!
//! ## Call the dispatcher, not the suffixed variant
//!
//! The operation closure should call your **public dispatcher** — the function
//! that internally does `incant!` or was generated by `#[autoversion]`. Do NOT
//! call a specific tier variant like `process_v3()`:
//!
//! ```rust,ignore
//! // GOOD: calls the dispatcher — dispatch falls back as tokens are disabled
//! check_simd_consistency(
//!     || {
//!         let output = my_resize(&input, 256, 256);  // dispatches internally
//!         (output.to_rgba8(), 256, 256)
//!     },
//!     &RegressionTolerance::off_by_one(),
//!     CompileTimePolicy::Warn,
//! );
//!
//! // BAD: calls a specific tier — won't test fallback paths
//! check_simd_consistency(
//!     || {
//!         let t = X64V3Token::summon().unwrap();
//!         let output = my_resize_v3(t, &input, 256, 256);  // always V3
//!         (output.to_rgba8(), 256, 256)
//!     },
//!     ...
//! );
//! ```
//!
//! `for_each_token_permutation` disables tokens at the process level, so when
//! V3 is disabled, `X64V3Token::summon()` returns `None` and the dispatcher
//! falls through to V2 or scalar. This is how you test all tiers without
//! calling each one explicitly.
//!
//! ## Functions with token parameters
//!
//! If the function takes an explicit token (`#[arcane]` inner functions),
//! tokens are `Copy` — summon outside and capture, or use `incant!`:
//!
//! ```rust,ignore
//! use archmage::incant;
//!
//! check_simd_consistency(
//!     || {
//!         // incant! summons the best available token and dispatches
//!         let output = incant!(process_row(&input), [v3, neon, scalar]);
//!         (output, 256, 256)
//!     },
//!     &RegressionTolerance::off_by_one(),
//!     CompileTimePolicy::Warn,
//! );
//! ```
//!
//! `incant!` handles summoning and passing the right token type.
//! As `for_each_token_permutation` disables tokens, `incant!` falls back
//! to lower tiers automatically.
//!
//! ## Skipping crypto permutations
//!
//! On x86, crypto tokens (PCLMUL, AES) are independent from compute tiers
//! (AVX2, FMA). Image processing code never uses crypto instructions, so
//! toggling them just multiplies permutations without testing anything new.
//!
//! Pass `CryptoGrouping::Skip` to exclude crypto tokens from permutations:
//!
//! ```rust,ignore
//! check_simd_consistency_opts(
//!     || { ... },
//!     &RegressionTolerance::off_by_one(),
//!     CompileTimePolicy::Warn,
//!     CryptoGrouping::Skip,
//! );
//! ```
//!
//! | Grouping | On AVX2+AES machine | Permutations |
//! |----------|---------------------|-------------|
//! | `Clump` (default) | Compute permutations + one crypto-all-off run | ~5 |
//! | `Skip` | V1, V2, V3 only, crypto untouched | ~4 |
//! | `Combinatorial` | Full cross-product of all tokens | ~16 |
//!
//! ## `#[autoversion]` functions
//!
//! `#[autoversion]` generates everything you need — suffixed variants plus a
//! public dispatcher that hides the token:
//!
//! ```rust,ignore
//! #[autoversion]
//! pub fn blur_row(data: &[f32], kernel: &[f32], out: &mut [f32]) {
//!     // scalar loop — compiler auto-vectorizes per tier
//!     for i in 0..out.len() { ... }
//! }
//!
//! // Generated: blur_row_v4, blur_row_v3, blur_row_neon, blur_row_scalar
//! // Plus: blur_row() dispatcher (no token param, public API)
//! ```
//!
//! Test through the dispatcher:
//!
//! ```rust,ignore
//! check_simd_consistency(
//!     || {
//!         let mut out = vec![0.0f32; w * h * 3];
//!         blur_row(&input, &kernel, &mut out);  // dispatcher
//!         let rgba = f32_to_rgba(&out, w, h);
//!         (rgba, w as u32, h as u32)
//!     },
//!     &RegressionTolerance::off_by_one(),
//!     CompileTimePolicy::Warn,
//! );
//! ```
//!
//! ## Combining with oracle testing
//!
//! Oracle and SIMD consistency are complementary:
//!
//! - **Oracle** (in [`crate::oracle`]) verifies the output is *correct*
//!   (matches the mathematical definition).
//! - **SIMD consistency** verifies all tiers are *equivalent* (match each other).
//!
//! Use both. A bug where all tiers produce the same wrong answer passes SIMD
//! consistency but fails oracle. A bug where only one tier diverges might pass
//! oracle (depending on which tier ran) but fails SIMD consistency.
//!
//! # CI integration
//!
//! For full permutation coverage in CI, compile with the `testable_dispatch`
//! feature on archmage and use `CompileTimePolicy::Fail`:
//!
//! ```toml
//! [dev-dependencies]
//! archmage = { version = "0.9", features = ["testable_dispatch"] }
//! zensim-regress = { version = "0.2", features = ["archmage"] }
//! ```

use std::fmt;

use archmage::testing::{
    CompileTimePolicy, PermutationReport, for_each_token_permutation, lock_token_testing,
};
use zensim::{RgbaSlice, Zensim, ZensimProfile};

use crate::error::RegressError;
use crate::testing::{RegressionReport, RegressionTolerance, check_regression};

// ─── Crypto grouping ────────────────────────────────────────────────────

/// Controls how crypto tokens (PCLMUL, AES, SHA) participate in SIMD
/// permutation testing.
///
/// On x86, crypto tokens are independent from compute tiers (AVX2, FMA).
/// Image processing code rarely uses crypto instructions, so toggling them
/// combinatorially with compute tiers multiplies test count without finding
/// real bugs.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum CryptoGrouping {
    /// Full combinatorial permutations of all tokens including crypto.
    /// Can be 2-4x more permutations than necessary for non-crypto code.
    /// Use when your code actually uses PCLMUL/AES/SHA instructions.
    Combinatorial,
    /// Exclude crypto tokens entirely. They stay at their natural state
    /// (enabled if the CPU has them) and don't participate in permutations.
    /// Best for image processing code that never uses PCLMUL/AES/SHA.
    Skip,
    /// Crypto tokens move as a single group: all enabled or all disabled,
    /// tested as a separate series from compute tiers. Produces
    /// `compute_perms + 1` instead of `compute_perms × crypto_perms`.
    /// Default — covers crypto without combinatorial explosion.
    #[default]
    Clump,
}

/// Token names that are crypto-only (not compute).
const CRYPTO_TOKEN_NAMES: &[&str] = &[
    "x86-64-crypto",    // X64CryptoToken (PCLMUL + AES)
    "x86-64-v3-crypto", // X64V3CryptoToken
    "aarch64-aes",      // NeonAesToken
    "aarch64-sha3",     // NeonSha3Token
];

fn is_crypto_token(name: &str) -> bool {
    CRYPTO_TOKEN_NAMES.contains(&name)
}

// ─── Report types ──────────────────────────────────────────────────────

/// Comparison of one SIMD tier against the reference (highest-tier) output.
#[derive(Debug, Clone)]
pub struct TierComparison {
    /// Human-readable tier label (e.g., "x86-64-v3 disabled").
    pub tier_label: String,
    /// Regression report comparing this tier's output against the reference.
    pub report: RegressionReport,
}

/// Result of running all SIMD tier permutations.
#[derive(Debug, Clone)]
pub struct SimdConsistencyReport {
    /// Label of the reference tier (first permutation, usually "all enabled").
    pub reference_tier: String,
    /// Total number of permutations executed.
    pub permutation_count: usize,
    /// Comparison of each non-reference tier against the reference.
    pub comparisons: Vec<TierComparison>,
    /// Whether all tier comparisons passed the tolerance.
    pub all_passed: bool,
    /// Underlying archmage permutation report (warnings, count).
    pub permutation_report: PermutationReport,
}

impl SimdConsistencyReport {
    /// Create a report for the degenerate case of a single permutation.
    fn single_tier(perm_report: PermutationReport) -> Self {
        Self {
            reference_tier: "all enabled".to_string(),
            permutation_count: 1,
            comparisons: Vec::new(),
            all_passed: true,
            permutation_report: perm_report,
        }
    }
}

impl fmt::Display for SimdConsistencyReport {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let status = if self.all_passed { "PASS" } else { "FAIL" };

        writeln!(
            f,
            "{status}: SIMD consistency across {} permutations (ref: {}).",
            self.permutation_count, self.reference_tier,
        )?;

        for cmp in &self.comparisons {
            let tier_status = if cmp.report.passed() { " " } else { "x" };
            writeln!(
                f,
                "  {tier_status} {}: score={:.1}, max_delta={:?}, category={:?}",
                cmp.tier_label,
                cmp.report.score(),
                cmp.report.max_channel_delta(),
                cmp.report.category(),
            )?;
        }

        for w in &self.permutation_report.warnings {
            writeln!(f, "  warning: {w}")?;
        }

        Ok(())
    }
}

// ─── Public API ────────��──────────────────────���─────────────────────────

/// Run `operation` under every SIMD token permutation and compare outputs.
///
/// Convenience wrapper for [`check_simd_consistency_opts`] with
/// [`CryptoGrouping::Clump`] (default — crypto tested as a group,
/// not combinatorially with compute tiers).
pub fn check_simd_consistency(
    operation: impl Fn() -> (Vec<u8>, u32, u32),
    tolerance: &RegressionTolerance,
    policy: CompileTimePolicy,
) -> Result<SimdConsistencyReport, RegressError> {
    check_simd_consistency_opts(operation, tolerance, policy, CryptoGrouping::default())
}

/// Run `operation` under SIMD token permutations with crypto grouping control.
///
/// The operation closure is called once per permutation. It must return
/// `(rgba_pixels, width, height)` — RGBA u8 format.
///
/// All outputs are compared against the first permutation (highest SIMD
/// tier, typically "all enabled") using the provided tolerance.
///
/// # Arguments
///
/// * `operation` — Closure returning `(Vec<u8>, u32, u32)` — RGBA pixels, width, height.
/// * `tolerance` — How closely non-reference tiers must match the reference.
///   [`RegressionTolerance::off_by_one()`] is a good default.
/// * `policy` — What to do when tokens can't be disabled. Use `Warn` locally,
///   `Fail` in CI with `testable_dispatch`.
/// * `crypto` — How to handle crypto tokens. [`CryptoGrouping::Skip`] is
///   recommended for image processing code.
///
/// # Errors
///
/// Returns [`RegressError`] if zensim comparison fails (dimension mismatch).
pub fn check_simd_consistency_opts(
    operation: impl Fn() -> (Vec<u8>, u32, u32),
    tolerance: &RegressionTolerance,
    policy: CompileTimePolicy,
    crypto: CryptoGrouping,
) -> Result<SimdConsistencyReport, RegressError> {
    let mut outputs: Vec<(String, Vec<u8>, u32, u32)> = Vec::new();

    let perm_report = match crypto {
        CryptoGrouping::Combinatorial => {
            // Full combinatorial — existing behavior
            for_each_token_permutation(policy, |perm| {
                let (pixels, w, h) = operation();
                outputs.push((perm.label.clone(), pixels, w, h));
            })
        }
        CryptoGrouping::Skip => {
            // Filter: run all permutations but only collect when the disabled
            // set contains no crypto tokens (or is identical to a crypto-only
            // difference we already collected).
            let mut seen_compute_states: Vec<Vec<String>> = Vec::new();
            for_each_token_permutation(policy, |perm| {
                // Extract the compute-only disabled set
                let compute_disabled: Vec<String> = perm
                    .disabled
                    .iter()
                    .filter(|name| !is_crypto_token(name))
                    .map(|&s| s.to_string())
                    .collect();

                // Skip if we've already seen this compute state
                if seen_compute_states.contains(&compute_disabled) {
                    return;
                }
                seen_compute_states.push(compute_disabled);

                let (pixels, w, h) = operation();
                let label = if perm.disabled.is_empty() {
                    perm.label.clone()
                } else {
                    // Relabel to show only compute tokens
                    let compute_names: Vec<&str> = perm
                        .disabled
                        .iter()
                        .filter(|name| !is_crypto_token(name))
                        .copied()
                        .collect();
                    if compute_names.is_empty() {
                        "all enabled".to_string()
                    } else {
                        format!("{} disabled", compute_names.join(", "))
                    }
                };
                outputs.push((label, pixels, w, h));
            })
        }
        CryptoGrouping::Clump => {
            // Two series: (1) compute permutations with crypto at natural state,
            // (2) one extra run with all crypto disabled (if any crypto is available).
            // Series 1: same as Skip — get compute permutations
            let mut seen_compute_states: Vec<Vec<String>> = Vec::new();
            let mut has_crypto = false;
            let report = for_each_token_permutation(policy, |perm| {
                if perm.disabled.iter().any(|name| is_crypto_token(name)) {
                    has_crypto = true;
                }

                let compute_disabled: Vec<String> = perm
                    .disabled
                    .iter()
                    .filter(|name| !is_crypto_token(name))
                    .map(|&s| s.to_string())
                    .collect();

                if seen_compute_states.contains(&compute_disabled) {
                    return;
                }
                seen_compute_states.push(compute_disabled);

                let (pixels, w, h) = operation();
                let label = if perm.disabled.is_empty() {
                    perm.label.clone()
                } else {
                    let compute_names: Vec<&str> = perm
                        .disabled
                        .iter()
                        .filter(|name| !is_crypto_token(name))
                        .copied()
                        .collect();
                    if compute_names.is_empty() {
                        "all enabled".to_string()
                    } else {
                        format!("{} disabled", compute_names.join(", "))
                    }
                };
                outputs.push((label, pixels, w, h));
            });

            // Series 2: if crypto tokens exist, run once with all crypto disabled
            // (compute at highest tier). This is inside the permutation lock,
            // but for_each_token_permutation already ran and cleaned up.
            if has_crypto {
                // We need to manually disable crypto tokens for one run.
                // Acquire the lock (for_each_token_permutation released it).
                let _lock = lock_token_testing();
                disable_crypto_tokens(true);

                let (pixels, w, h) = operation();
                outputs.push(("all crypto disabled".to_string(), pixels, w, h));

                disable_crypto_tokens(false);
            }

            report
        }
    };

    compare_outputs(outputs, perm_report, tolerance)
}

/// Compare collected outputs against the reference (first entry).
fn compare_outputs(
    outputs: Vec<(String, Vec<u8>, u32, u32)>,
    perm_report: PermutationReport,
    tolerance: &RegressionTolerance,
) -> Result<SimdConsistencyReport, RegressError> {
    if outputs.len() < 2 {
        return Ok(SimdConsistencyReport::single_tier(perm_report));
    }

    let zensim = Zensim::new(ZensimProfile::latest());

    let ref_label = outputs[0].0.clone();
    let ref_w = outputs[0].2 as usize;
    let ref_h = outputs[0].3 as usize;
    let ref_pixels: Vec<[u8; 4]> = outputs[0]
        .1
        .chunks_exact(4)
        .map(|c| [c[0], c[1], c[2], c[3]])
        .collect();
    let ref_img = RgbaSlice::new(&ref_pixels, ref_w, ref_h);

    let mut comparisons = Vec::new();
    let mut all_passed = true;

    for (label, px, w, h) in &outputs[1..] {
        let actual_pixels: Vec<[u8; 4]> = px
            .chunks_exact(4)
            .map(|c| [c[0], c[1], c[2], c[3]])
            .collect();
        let actual_img = RgbaSlice::new(&actual_pixels, *w as usize, *h as usize);

        let report = check_regression(&zensim, &ref_img, &actual_img, tolerance).map_err(|e| {
            RegressError::Io {
                path: std::path::PathBuf::from("<simd-comparison>"),
                source: std::io::Error::other(e.to_string()),
            }
        })?;

        if !report.passed() {
            all_passed = false;
        }
        comparisons.push(TierComparison {
            tier_label: label.clone(),
            report,
        });
    }

    Ok(SimdConsistencyReport {
        reference_tier: ref_label,
        permutation_count: outputs.len(),
        comparisons,
        all_passed,
        permutation_report: perm_report,
    })
}

/// Disable or re-enable all crypto tokens. Best-effort — ignores errors
/// from compile-time-guaranteed tokens.
fn disable_crypto_tokens(disabled: bool) {
    #[cfg(any(target_arch = "x86_64", target_arch = "x86"))]
    {
        let _ = archmage::X64CryptoToken::dangerously_disable_token_process_wide(disabled);
        let _ = archmage::X64V3CryptoToken::dangerously_disable_token_process_wide(disabled);
    }
    #[cfg(target_arch = "aarch64")]
    {
        let _ = archmage::NeonAesToken::dangerously_disable_token_process_wide(disabled);
        let _ = archmage::NeonSha3Token::dangerously_disable_token_process_wide(disabled);
    }
}

/// Run `operation` under every SIMD token permutation (f32 variant).
///
/// Same as [`check_simd_consistency`] but for float pixel data.
/// Output f32 pixels are quantized to u8 RGBA for zensim comparison.
///
/// The operation returns `(Vec<f32>, u32, u32, usize)` — pixel data,
/// width, height, channels (1–4).
pub fn check_simd_consistency_f32(
    operation: impl Fn() -> (Vec<f32>, u32, u32, usize),
    tolerance: &RegressionTolerance,
    policy: CompileTimePolicy,
) -> Result<SimdConsistencyReport, RegressError> {
    check_simd_consistency(
        || {
            let (data, w, h, ch) = operation();
            let rgba = f32_to_rgba8(&data, w, h, ch);
            (rgba, w, h)
        },
        tolerance,
        policy,
    )
}

/// Convert f32 pixel data to RGBA u8, clamping to 0–255.
fn f32_to_rgba8(data: &[f32], w: u32, h: u32, channels: usize) -> Vec<u8> {
    let pixel_count = w as usize * h as usize;
    let mut rgba = Vec::with_capacity(pixel_count * 4);

    for i in 0..pixel_count {
        let offset = i * channels;
        let r = (data.get(offset).copied().unwrap_or(0.0) * 255.0)
            .round()
            .clamp(0.0, 255.0) as u8;
        let g = if channels > 1 {
            (data[offset + 1] * 255.0).round().clamp(0.0, 255.0) as u8
        } else {
            r
        };
        let b = if channels > 2 {
            (data[offset + 2] * 255.0).round().clamp(0.0, 255.0) as u8
        } else {
            r
        };
        let a = if channels > 3 {
            (data[offset + 3] * 255.0).round().clamp(0.0, 255.0) as u8
        } else {
            255
        };
        rgba.extend_from_slice(&[r, g, b, a]);
    }

    rgba
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::generators;

    #[test]
    fn single_permutation_passes() {
        // On most dev machines without testable_dispatch, all tokens are
        // compile-time guaranteed → single permutation.
        let input = generators::gradient(64, 64);

        let report = check_simd_consistency(
            || (input.clone(), 64, 64),
            &RegressionTolerance::exact(),
            CompileTimePolicy::Warn,
        )
        .unwrap();

        assert!(report.all_passed, "{report}");
        // May have 1 or more permutations depending on build flags
        assert!(report.permutation_count >= 1);
    }

    #[test]
    fn f32_variant_works() {
        let w = 32u32;
        let h = 32u32;
        let data: Vec<f32> = (0..w * h * 3)
            .map(|i| (i as f32) / (w * h * 3) as f32)
            .collect();

        let report = check_simd_consistency_f32(
            || (data.clone(), w, h, 3),
            &RegressionTolerance::exact(),
            CompileTimePolicy::Warn,
        )
        .unwrap();

        assert!(report.all_passed, "{report}");
    }

    #[test]
    fn report_display_format() {
        let report = SimdConsistencyReport {
            reference_tier: "all enabled".to_string(),
            permutation_count: 3,
            comparisons: Vec::new(),
            all_passed: true,
            permutation_report: PermutationReport {
                warnings: Vec::new(),
                permutations_run: 3,
            },
        };
        let s = format!("{report}");
        assert!(s.contains("PASS"));
        assert!(s.contains("3 permutations"));
    }
}
